import {Dimensions, StyleSheet} from 'react-native';

const {width, height} = Dimensions.get('screen');

const commonStyles = StyleSheet.create({
  modalCard: {
    height: 0.8 * height,
    width: '100%',
    marginTop: 0.312 * height,
    backgroundColor: '#FFFFFF',
    borderRadius: 38,
  },
  inputText: {
    fontFamily: 'Lato-Regular',
    fontSize: 16,
    lineHeight: 19,
  },
  topContainer: {
    height: 0.034 * height,
    width: 0.813 * width,
    marginTop: 0.0233 * height,
    marginLeft: 0.093 * width,
  },
  resetPassButtonContainerEnabled: {
    height: 37,
    width: 211,
    borderRadius: 18,
    marginTop: 60,
    marginLeft: 88.5,
    borderStyle: 'solid',
    borderColor: '#E6E5E5',
    borderWidth: 1,
    textAlign: 'center',
    backgroundColor: '#7BA8A5',
  },
  otherContainer: {
    height: 0.034 * height,
    width: 0.813 * width,
    marginTop: 0.06 * height,
    marginLeft: 36,
  },
  topText: {
    height: 0.039 * height,
    width: 0.69 * width,
    color: '#000000',
    fontFamily: 'Lato',
    fontSize: 26,
    fontWeight: 'bold',
    lineHeight: 0.039 * height,
    marginTop: 0.053 * height,
    marginLeft: 0.099 * width,
  },
  buttonTextEnabled: {
    color: '#FFFFFF',
    fontFamily: 'Lato-Regular',
    fontSize: 14,
    lineHeight: 14,
    textAlign: 'center',
    paddingTop: 11.5,
  },
  buttonTextDisabled: {
    color: '#9B9B9B',
    fontFamily: 'Lato-Regular',
    fontSize: 14,
    lineHeight: 14,
    textAlign: 'center',
    paddingTop: 11.5,
  },
  labelStyle: {
    fontFamily: 'Lato-Regular',
    fontSize: 12,
    lineHeight: 15,
    alignItems: 'center',
    color: '#CAC9CB',
  },
  iconStyle: {
    height: 18,
    width: 24,
  },
  accountBottom: {
    flexDirection: 'row',
    marginTop: 28,
    height: 15,
    width: 335,
    marginLeft: 25,
    textAlign: 'center',
    justifyContent: 'center',
  },
  accountBottomText: {
    color: '#9B9B9B',
    fontFamily: 'ProximaNova-Regular',
    fontSize: 12,
    lineHeight: 15,
  },
  accountBottomLink: {
    color: '#4A90E2',
    fontFamily: 'ProximaNova-Regular',
    fontSize: 12,
    lineHeight: 15,
  },
  passwordValidationCheck: {
    marginTop: 64,
    marginLeft: 38,
    width: 305,
    height: 30,
    justifyContent: 'center',
  },
  passwordTextOk: {
    flex: 1,
    flexWrap: 'wrap',
    color: '#707BAE',
    textAlign: 'left',
    fontFamily: 'Proxima Nova',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 15,
  },
  passwordTextNotOk: {
    color: '#CAC9CB',
    flexWrap: 'wrap',
    textAlign: 'left',
    flex: 1,
    fontFamily: 'Proxima Nova',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 15,
  },
  inputErrorStyle: {
    height: 15,
    width: 265,
    color: '#E38A75',
    fontFamily: 'Lato',
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 15,
    marginLeft: 35,
  },
  login: {
    position: 'absolute',
    marginLeft: 0.515 * width,
  },
  loginContainer: {
    width: 42,
    height: 42,
    borderRadius: 100 / 2,
    marginLeft: 167,
    marginTop: 54,
  },
  loginCircle: {
    width: 42,
    height: 42,
    borderRadius: 100 / 2,
    backgroundColor: '#7BA8A5',
    justifyContent: 'space-between',
  },
  keyboardArrowRight: {
    color: 'white',
  },
  errorText: {
    color: 'red',
  },
  modalCardStyle: {
    backgroundColor: 'transparent',
    opacity: 1.0,
  },
  modalContainerStyle: {
    backgroundColor: 'transparent',
  },
  streetViewMapContainer: {
    // border: 0,
    marginLeft: '-2.5%',
    width: '105%',
    height: 350,
    flex: 0,
    position: 'absolute',
    zIndex: 1,
    // frameBorder: 0,
  },
});

export default commonStyles;
